signInBtn = '//a[@class="HeaderMenu-link no-underline mr-3"]'
emailTxt = '//input[@id="login_field"]'
passwordTxt = '//input[@id="password"]'
loginBtn = '//input[@class="btn btn-primary btn-block"]'
validateLoggedin = '//h1[@class="float-none flex-auto pl-0 width-fit"]'
loginError = '//div[@id="js-flash-container"]'
createGistLink = '//a[@href="/"]'
descTxt = '//input[@class="form-control input-block input-contrast"]'
fileNamingTxt = '//input[@class="form-control filename js-gist-filename js-blob-filename"]'
createLine1 = '//div[@class="CodeMirror-code"]'
selectPublish = '//summary[@class="btn btn-primary BtnGroup-item select-menu-button float-none"]'
publicBtn = '//span[text()="Create public gist"]'
secretBtn = '//span[text()="Create secret gist"]'
editGistLink = '//a[@class="btn btn-sm"]'
updateBtn = '//button[@class="btn btn-primary"]'
deleteGistLink = '/button[@class="btn btn-sm btn-danger" and @type="submit"]'
validateDeleted = '//div[@class="container"]'
validateList = '//a[@class="js-selected-navigation-item selected reponav-item"]'